### ISSUE TITLE
[META: Ideas for near future]

### ISSUE THREAD

**Issue by dmpe** [Chicago/RSocrata#50]
This is meta issue (for myself; label would be nice however)

- [x] conform to style : http://adv-r.had.co.nz/Style.html /  Google R
- [x] replace `2015-07-10 11:18:47.945 getResponse: Error in httr GET: 401  http://data.cityofchicago.org/resource/j8vp-2qpg.json`
with a nice message/warning/stop functions #48, #53 
- [x] close all issues which need to be closed
- [x] #43

See also
https://github.com/Chicago/RSocrata/wiki/Roadmap#planned-releases

**Comment by dmpe** [comment]
@geneorama 
How does it look with the `sprint7` branch ? So many good changes but not merged. 

Many changes are very good fixing bugs such as #19.

**Comment by tomschenkjr** [comment]
@dmpe- 
* Yeah. We're going to modify it a bit since we have some ways we approach things (e.g., `package::function`).
* Absolutely, we need some better error handling for HTTP issues instead of relying on httr's returns. Will help with the unit testing issues Issue #16 is similar and is need
* On closing issues, they're often closed when we finally push to master since "closing" is included in the commit message.
* @geneorama changes--as a whole--were pretty big and are aiming to be incorporated in the [v2](https://github.com/Chicago/RSocrata/wiki/Roadmap#version-20) of the package. I see some new functions or at least the structure of functions needing to change because of the new [API functionality](http://dev.socrata.com/changelog/) (e.g., #43). 

We may want to make some of these changes in minor and bug releases. For instance, 1.6.2 to split R files and better error handling. Then #43 can be slated for v1.7 or 2.0 depending if we get this all done at once. However, I think we need to change the function syntax a bit (see sprint7 branch) to accomidate some of Socrata's new API functionality.

I've updated the roadmap to reflect some of these desires in version 2.0.
